name: "longformerNER_kaggle_exp"

model_savename: "longformer"
model_name: 'aditya140/longformerNER_kaggle'

max_length: 1024
inference_max_length: 4096
train_batch_size: 6
valid_batch_size: 6
lr: 4e-5

num_labels: 15
label_subtokens: True
output_hidden_states: True
hidden_dropout_prob: 0.1
layer_norm_eps: 1e-7
add_pooling_layer: False

n_epoch: 2 # not to exceed runtime limit
n_fold: 5
verbose_steps: 500
random_seed: 42

is_debug: False
# debug_sample: 1000
# verbose_steps: 16
# n_epoch: 1
# n_fold: 2

